version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: prm_db
      POSTGRES_USER: prm_user
      POSTGRES_PASSWORD: prm_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - prm_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - prm_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://prm_user:prm_password@db:5432/prm_db
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - prm_network

  celery:
    build: .
    command: celery -A prm_backend worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://prm_user:prm_password@db:5432/prm_db
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - prm_network

  celery-beat:
    build: .
    command: celery -A prm_backend beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://prm_user:prm_password@db:5432/prm_db
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - prm_network

volumes:
  postgres_data:

networks:
  prm_network:
    driver: bridge
